namespace: "codeaffen"
name: "phpipam"
description: Ansible Modules to manage phpIPAM installations
authors:
  - "Christian Meißner <cme@codeaffen.org>"
  - "Andreas Klamke <andy@klamke.net>"
  - "Billy Longman <bill.longman@summit-broadband.com>"
  - "Mario Fritschen <github@fritschen.net>"
  - "lush <porous@web.de>"
version: "1.3.1"
license:
  - "GPL-3.0-or-later"
tags:
  - api
  - networking
  - phpipam
  - system
readme: "README.md"
homepage: "https://codeaffen.org/projects/phpipam-ansible-modules"
repository: "https://github.com/codeaffen/phpipam-ansible-modules"
issues: "https://github.com/codeaffen/phpipam-ansible-modules/issues"
