name: CI

on: [push, pull_request]

jobs:
  test:
    name: end to end tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        phpipam-version: ['v1.4x', 'v1.5x']
    steps:
      - uses: actions/checkout@v3
      - name: setup phpipam
        uses: codeaffen/phpipam-action@v2
        with:
          ipam_version: ${{ matrix.phpipam-version }}
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: setup test environment
        run: |
          make test-setup
        env:
          PHPIPAM_URL: "https://localhost"
          PHPIPAM_APPID: "ansible"
          PHPIPAM_USERNAME: "admin"
          PHPIPAM_PASSWORD: "ipamadmin"
      - name: run example setup
        run: |
          make test-example_setup
        env:
          PHPIPAM_VALIDATE_CERTS: false
      - name: run playbook tests
        run: |
          make test-all
        env:
          PHPIPAM_VALIDATE_CERTS: "false"
