name: "Push Notification"
on: [push, pull_request, create]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: irc push
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'push'
        with:
          channel: ${{ secrets.LIBERA_CHATBOT_CHANNEL }}
          server: "irc.libera.chat"
          nickname: ${{ secrets.LIBERA_CHATBOT_USERNAME }}
          sasl_password: ${{ secrets.LIBERA_CHATBOT_PASSWORD }}
          message: |
            ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
      - name: irc pull request
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'pull_request'
        with:
          channel: ${{ secrets.LIBERA_CHATBOT_CHANNEL }}
          server: "irc.libera.chat"
          nickname: ${{ secrets.LIBERA_CHATBOT_USERNAME }}
          sasl_password: ${{ secrets.LIBERA_CHATBOT_PASSWORD }}
          message: |
            ${{ github.actor }} opened PR ${{ github.event.pull_request.html_url }}
      - name: irc tag created
        uses: rectalogic/notify-irc@v1
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        with:
          channel: ${{ secrets.LIBERA_CHATBOT_CHANNEL }}
          server: "irc.libera.chat"          
          nickname: ${{ secrets.LIBERA_CHATBOT_USERNAME }}
          sasl_password: ${{ secrets.LIBERA_CHATBOT_PASSWORD }}
          message: |
            ${{ github.actor }} tagged ${{ github.repository }} ${{ github.event.ref }}